schema = 3

[mod]
  [mod."github.com/adrg/xdg"]
    version = "v0.4.0"
    hash = "sha256-zGjkdUQmrVqD6rMO9oDY+TeJCpuqnHyvkPCaXDlac/U="
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.13.0"
    hash = "sha256-fYwAHQFWGWzcMO8XPNzR7iAUarVGMKJjfX1DB74AmrA="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.0.5"
    hash = "sha256-/qS8wU8yZQJ+uTOg66rEl9s7spxq9VIXF5L1BcaEClc="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/barasher/go-exiftool"]
    version = "v1.10.0"
    hash = "sha256-ed+Jhji3usyMROzjw7Xq++khLz3mDrlgfn+vrBXWZgg="
  [mod."github.com/bodgit/plumbing"]
    version = "v1.3.0"
    hash = "sha256-nmLdJAB2sWpwHb2lFrYTcMR4yusMM1U629Pm2K9hfm0="
  [mod."github.com/bodgit/sevenzip"]
    version = "v1.4.0"
    hash = "sha256-1y3jeuXQPEYWe8iuOhplbHtZjN2GgAXDnJaJohDMwLc="
  [mod."github.com/bodgit/windows"]
    version = "v1.0.1"
    hash = "sha256-GSpAGboli54A5wDMpDEdZDYh55o1Zs8dZzFIf7hYdMY="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.18.0"
    hash = "sha256-FVKLet2anNB6gupLYXO4kJaKQIXs1dg2dZ2ooaBiEZU="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.26.2"
    hash = "sha256-s91dQE2wL7VDfQo0UDK0RRySSpUeGgrCHbSKhYEodvM="
  [mod."github.com/charmbracelet/harmonica"]
    version = "v0.2.0"
    hash = "sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.10.0"
    hash = "sha256-JZD1iVeizYe0mp3qQcJbUZdYN6HP/DNC67ja79DTe6s="
  [mod."github.com/charmbracelet/x/exp/term"]
    version = "v0.0.0-20240522154747-75cd6ffa5c81"
    hash = "sha256-nFtz7oWQh5L9nIAuY1cW7KOJJ33QsTPSz9HyiNIYRYc="
  [mod."github.com/connesc/cipherio"]
    version = "v0.2.1"
    hash = "sha256-PeuFnTak2WADesP8YTBqHP/XyvBue9bdKHYser2v6LU="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.4"
    hash = "sha256-pQ+H8Psh92KWTang8hK0cHFLomH+4X0rMMilIJUQ4Qc="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/deckarep/golang-set"]
    version = "v1.8.0"
    hash = "sha256-ELJKphksU9AOYwV3BtjvwPtUpbZvX9YMmo7eIiauQSc="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.11.0"
    hash = "sha256-iXBBgykYu9Dcd+7LMJyRYc3Ry47jmuLGZFW13zU6toU="
  [mod."github.com/erikgeiser/coninput"]
    version = "v0.0.0-20211004153227-1c3628e74d0f"
    hash = "sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.2.6"
    hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/kdomanski/iso9660"]
    version = "v0.3.3"
    hash = "sha256-iMyzZnZCKXUfBKJDdqwEYyzcFKo/VEkoo4Lm/Ct8tj4="
  [mod."github.com/klauspost/compress"]
    version = "v1.16.3"
    hash = "sha256-dU0OgO5afQ1z5s83Y3w8Bg0ftvg+ikWbktUACEgY3OQ="
  [mod."github.com/lithammer/shortuuid"]
    version = "v3.0.0+incompatible"
    hash = "sha256-dD6ArCHGnpo84RBy6SI2kUjMqHS4IZU+K+DgAgmRakY="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/masatana/go-textdistance"]
    version = "v0.0.0-20191005053614-738b0edac985"
    hash = "sha256-oFZqvacgNt5uHrfRCzpR2Z6BRGRepbhKdD+sU9PUCVo="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.18"
    hash = "sha256-QpIn0DSggtBn2ocyj0RlXDKLK5F5KZG1/ogzrqBCjF8="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.2"
    hash = "sha256-Eum/SpyytcNIchANPkG4bYGBgcezLgej7j/+6IhqoMU="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/nwaples/rardecode"]
    version = "v1.1.3"
    hash = "sha256-X7Cg0kEygyy6Xw6sxRF9HirgefkH9tn9UPPelxRaAGg="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.2"
    hash = "sha256-ukxk1Cfm6cQW18g/aa19tLcUu5BnF7VmfAvrDHAOl6A="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.17"
    hash = "sha256-36L+GNhRrHBCyhbHCqweCk5rfmggdRtHqH6g5m1ViQI="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/rkoesters/xdg"]
    version = "v0.0.1"
    hash = "sha256-+ckoKNaiEqQIpRFPr3CNRE3w8+OHmRKZ2cn6MquNIOE="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shirou/gopsutil"]
    version = "v3.21.11+incompatible"
    hash = "sha256-tcH5zN94yZhKtg8wAUfojlqdyguifuPTBLPso3KF7QA="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.11"
    hash = "sha256-SUyrjc2wyN3cTGKe5JdBEXjtZC1rJySRxJHVUZ59row="
  [mod."github.com/urfave/cli/v2"]
    version = "v2.27.2"
    hash = "sha256-P0yLmx2a2hIQjQ/RXKLG8ehI5eVivnettuMFr8MznFY="
  [mod."github.com/xrash/smetrics"]
    version = "v0.0.0-20240312152122-5f08fbb34913"
    hash = "sha256-ySUTdeoOUi3QcLEJBYvCDIhVrsrD2Ks6/4V9n4hCvBk="
  [mod."github.com/yorukot/ansichroma"]
    version = "v0.1.0"
    hash = "sha256-aIQZ16auuGfGLltKt2lm2T83f4sALrmRpOujxQepkS4="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."go4.org"]
    version = "v0.0.0-20230225012048-214862532bf5"
    hash = "sha256-8y7krSESdxZfxTzo16EDqmF8USRzGmLPYr3iKuVYzzE="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.20.0"
    hash = "sha256-mowlaoG2k4n1c1rApWef5EMiXd3I77CsUi8jPh6pTYA="
  [mod."golang.org/x/term"]
    version = "v0.20.0"
    hash = "sha256-kU+OVJbYktTIn4ZTAdomsOjL069Vj45sdroEMRKaRDI="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golift.io/xtractr"]
    version = "v0.2.2"
    hash = "sha256-ihKdIrWG1DKADjQ4X1AW62EGZWGgYU+9dY3g260bNOY="
