schema = 3

[mod]
  [mod."github.com/BourgeoisBear/rasterm"]
    version = "v1.1.2"
    hash = "sha256-fYV85hVcIAT01xriEpWn0f/YyGgsc7W+0SW6iz9K/+A="
  [mod."github.com/adrg/xdg"]
    version = "v0.5.3"
    hash = "sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs="
  [mod."github.com/alecthomas/chroma/v2"]
    version = "v2.21.1"
    hash = "sha256-N6ske1LCEJy7MZS1L/0DEaWXnWlVqGaoU6oCwrM5teQ="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.0.5"
    hash = "sha256-/qS8wU8yZQJ+uTOg66rEl9s7spxq9VIXF5L1BcaEClc="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/barasher/go-exiftool"]
    version = "v1.10.0"
    hash = "sha256-ed+Jhji3usyMROzjw7Xq++khLz3mDrlgfn+vrBXWZgg="
  [mod."github.com/bodgit/plumbing"]
    version = "v1.3.0"
    hash = "sha256-nmLdJAB2sWpwHb2lFrYTcMR4yusMM1U629Pm2K9hfm0="
  [mod."github.com/bodgit/sevenzip"]
    version = "v1.4.0"
    hash = "sha256-1y3jeuXQPEYWe8iuOhplbHtZjN2GgAXDnJaJohDMwLc="
  [mod."github.com/bodgit/windows"]
    version = "v1.0.1"
    hash = "sha256-GSpAGboli54A5wDMpDEdZDYh55o1Zs8dZzFIf7hYdMY="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.21.0"
    hash = "sha256-cfjUHgy9eq5SretTHuYuRaeeT6QmJYQBB9dsI8QSnW0="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v1.3.10"
    hash = "sha256-7wr85TLszu1CHNEMv+o4w+r24Z0xdzCgecPv+ZtRX/A="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.2.3-0.20250311203215-f60798e515dc"
    hash = "sha256-D9E/bMOyLXAUVOHA1/6o3i+vVmLfwIMOWib6sU7A6+Q="
  [mod."github.com/charmbracelet/harmonica"]
    version = "v0.2.0"
    hash = "sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v1.1.0"
    hash = "sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.10.1"
    hash = "sha256-nY4zkUGnuD+Lczwt+NMXdQ38cAsy5mtxzXrFSJmR0E4="
  [mod."github.com/charmbracelet/x/cellbuf"]
    version = "v0.0.13-0.20250311204145-2c3ea96c31dd"
    hash = "sha256-XAhCOt8qJ2vR77lH1ez0IVU1/2CaLTq9jSmrHVg5HHU="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.1"
    hash = "sha256-VBkCZLI90PhMasftGw3403IqoV7d3E5WEGAIVrN5xQM="
  [mod."github.com/clipperhouse/stringish"]
    version = "v0.1.1"
    hash = "sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.3.0"
    hash = "sha256-dLL70mEOxrmYVoQjy2K7QvZiahAlJKOcFDz2mW/R/Do="
  [mod."github.com/connesc/cipherio"]
    version = "v0.2.1"
    hash = "sha256-PeuFnTak2WADesP8YTBqHP/XyvBue9bdKHYser2v6LU="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.11.5"
    hash = "sha256-jN5+2ED+YbIoPIuyJ4Ou5pqJb2w1uNKzp5yTjKY6rEQ="
  [mod."github.com/ebitengine/purego"]
    version = "v0.9.1"
    hash = "sha256-iVfU8vaJ7IPa92dUeHeuW+yKvUbe59F/eV7GlDRIAcE="
  [mod."github.com/erikgeiser/coninput"]
    version = "v0.0.0-20211004153227-1c3628e74d0f"
    hash = "sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.2.6"
    hash = "sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hymkor/trash-go"]
    version = "v0.2.0"
    hash = "sha256-p7zJYJpPjNAYKRNW7No+BXRemNabGp/No1mp9ItHXII="
  [mod."github.com/kdomanski/iso9660"]
    version = "v0.3.3"
    hash = "sha256-iMyzZnZCKXUfBKJDdqwEYyzcFKo/VEkoo4Lm/Ct8tj4="
  [mod."github.com/klauspost/compress"]
    version = "v1.16.3"
    hash = "sha256-dU0OgO5afQ1z5s83Y3w8Bg0ftvg+ikWbktUACEgY3OQ="
  [mod."github.com/lazysegtree/go-zoxide"]
    version = "v0.1.0"
    hash = "sha256-PKEV+zCKf/7MsFAMMctL/pFSnEsri1yS8Bzxcj1dLWE="
  [mod."github.com/lithammer/shortuuid"]
    version = "v3.0.0+incompatible"
    hash = "sha256-dD6ArCHGnpo84RBy6SI2kUjMqHS4IZU+K+DgAgmRakY="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.3.0"
    hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.19"
    hash = "sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.16.0"
    hash = "sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI="
  [mod."github.com/nwaples/rardecode"]
    version = "v1.1.3"
    hash = "sha256-X7Cg0kEygyy6Xw6sxRF9HirgefkH9tn9UPPelxRaAGg="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.17"
    hash = "sha256-36L+GNhRrHBCyhbHCqweCk5rfmggdRtHqH6g5m1ViQI="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/power-devops/perfstat"]
    version = "v0.0.0-20240221224432-82ca36839d55"
    hash = "sha256-ujzuJ1ttQgjHQJEij4O/2+I8DZaUVZQCQgA4ysfqulI="
  [mod."github.com/reinhrst/fzf-lib"]
    version = "v0.9.0"
    hash = "sha256-UUe5g+oXopDj+JjvzAguqJ70/a4pqZhn7pdJiFE97yI="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/rkoesters/xdg"]
    version = "v0.0.1"
    hash = "sha256-+ckoKNaiEqQIpRFPr3CNRE3w8+OHmRKZ2cn6MquNIOE="
  [mod."github.com/rwcarlsen/goexif"]
    version = "v0.0.0-20190401172101-9e8deecbddbd"
    hash = "sha256-AiY2T9hXj6jnfldYDoe4WNr3FldpVTxc3lScR++HOLc="
  [mod."github.com/shirou/gopsutil/v4"]
    version = "v4.25.12"
    hash = "sha256-gzk9GW4+tXUWmxAVD3by/k4D/+l++TvajRVTkQJvwmM="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.14"
    hash = "sha256-21oXcIVmFyw+ukGQtflly0wpqaqh1jE0C9hLDSFYR7E="
  [mod."github.com/urfave/cli/v3"]
    version = "v3.6.1"
    hash = "sha256-q1WeKEvWoSyA0Wcan+Edjm71e0/vnPmqVvlfjUix7+8="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."github.com/yorukot/ansichroma"]
    version = "v0.1.0"
    hash = "sha256-aIQZ16auuGfGLltKt2lm2T83f4sALrmRpOujxQepkS4="
  [mod."github.com/yusufpapurcu/wmi"]
    version = "v1.2.4"
    hash = "sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA="
  [mod."go4.org"]
    version = "v0.0.0-20230225012048-214862532bf5"
    hash = "sha256-8y7krSESdxZfxTzo16EDqmF8USRzGmLPYr3iKuVYzzE="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20231006140011-7918f672742d"
    hash = "sha256-2SO1etTQ6UCUhADR5sgvDEDLHcj77pJKCIa/8mGDbAo="
  [mod."golang.org/x/image"]
    version = "v0.34.0"
    hash = "sha256-7V1bDhd++dCw11DCXOAUb5f1Hj51EfS0DZ03pq0V/p0="
  [mod."golang.org/x/mod"]
    version = "v0.30.0"
    hash = "sha256-tZJikWbjGgN5rCgB/dqj3dpn9BfAZUVyXmd3KavAgLE="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/term"]
    version = "v0.18.0"
    hash = "sha256-lpze9arFZIhBV8Ht3VZyoiUwqPkeH2IwfXt8M3xljiM="
  [mod."golang.org/x/text"]
    version = "v0.32.0"
    hash = "sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs="
  [mod."golift.io/xtractr"]
    version = "v0.2.2"
    hash = "sha256-ihKdIrWG1DKADjQ4X1AW62EGZWGgYU+9dY3g260bNOY="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
