##############################################
#                                            #
#                 0x96f Theme                #
#                                            #
##############################################

# This theme was created by: https://github.com/filipjanevski ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "monokai"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#fcfcfc"
full_screen_bg = "#262427"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#ff7272", "#bcdf59"]

#-- File Panel
file_panel_fg = "#fcfcfc"
file_panel_bg = "#262427"
file_panel_border = "#757075"
file_panel_border_active = "#ffca58"
file_panel_top_directory_icon = "#64d2e8"
file_panel_top_path = "#fcfcfc"
file_panel_item_selected_fg = "#c6e472"
file_panel_item_selected_bg = "#262427"

#-- Footer
footer_fg = "#fcfcfc"
footer_bg = "#262427"
footer_border = "#757075"
footer_border_active = "#ffca58"

#-- Sidebar
sidebar_fg = "#fcfcfc"
sidebar_bg = "#262427"
sidebar_title = "#64d2e8"
sidebar_border = "#757075"
sidebar_border_active = "#baebf6"
sidebar_item_selected_fg = "#c6e472"
sidebar_item_selected_bg = "#262427"
sidebar_divider = "#757075"

#-- Modals
modal_fg = "#fcfcfc"
modal_bg = "#262427"
modal_border_active = "#ffca58"
modal_cancel_fg = "#262427"
modal_cancel_bg = "#ff8787"
modal_confirm_fg = "#262427"
modal_confirm_bg = "#bcdf59"

#-- Help Menu
help_menu_hotkey = "#ff8787"
help_menu_title = "#64d2e8"

#-- Special
cursor = "#ffca58"
correct = "#c6e472"
error = "#ff8787"
hint = "#baebf6"
cancel = "#fcfcfc"
