##############################################
#                                            #
#                 Blood Theme                #
#                                            #
##############################################

# This theme was created by: https://github.com/charlesrocket ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "onedark"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#f8f8f2"
full_screen_bg = "#000000"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#720000", "#ff0000"]

#-- File Panel
file_panel_fg = "#f8f8f2"
file_panel_bg = "#000000"
file_panel_border = "#9a0000"
file_panel_border_active = "#ff0000"
file_panel_top_directory_icon = "#ff522e"
file_panel_top_path = "#ff9999"
file_panel_item_selected_fg = "#ff8d34"
file_panel_item_selected_bg = "#524549"

#-- Footer
footer_fg = "#f8f8f2"
footer_bg = "#000000"
footer_border = "#790000"
footer_border_active = "#ff0000"

#-- Sidebar
sidebar_fg = "#f8f8f2"
sidebar_bg = "#000000"
sidebar_title = "#dd0000"
sidebar_border = "#790000"
sidebar_border_active = "#ff0000"
sidebar_item_selected_fg = "#000000"
sidebar_item_selected_bg = "#ff8d34"
sidebar_divider = "#615250"

#-- Modals
modal_fg = "#f8f8f2"
modal_bg = "#000000"
modal_border_active = "#ff0000"
modal_cancel_fg = "#f9f9fe"
modal_cancel_bg = "#000042"
modal_confirm_fg = "#f9f9fe"
modal_confirm_bg = "#ffb86c"

#-- Help Menu
help_menu_hotkey = "#ff8d34"
help_menu_title = "#ff6666"

#-- Special
cursor = "#ff0000"
correct = "#47ef7d"
error = "#d70000"
hint = "#5bd9f3"
cancel = "#6575ab"
