##############################################
#                                            #
#         Catppuccin Macchiato Theme         #
#                                            #
##############################################

# This theme was created by: https://github.com/GV14982 ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-macchiato"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#a5adcb"
full_screen_bg = "#24273a"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#8aadf4", "#c6a0f6"]

#-- File Panel
file_panel_fg = "#a5adcb"
file_panel_bg = "#24273a"
file_panel_border = "#6e738d"
file_panel_border_active = "#b7bdf8"
file_panel_top_directory_icon = "#a6da95"
file_panel_top_path = "#8aadf4"
file_panel_item_selected_fg = "#91d7e3"
file_panel_item_selected_bg = "#24273a"

#-- Footer
footer_fg = "#a5adcb"
footer_bg = "#24273a"
footer_border = "#6e738d"
footer_border_active = "#a6da95"

#-- Sidebar
sidebar_fg = "#a5adcb"
sidebar_bg = "#24273a"
sidebar_title = "#7dc4e4"
sidebar_border = "#24273a"
sidebar_border_active = "#ed8796"
sidebar_item_selected_fg = "#91d7e3"
sidebar_item_selected_bg = "#24273a"
sidebar_divider = "#939ab7"

#-- Modals
modal_fg = "#a5adcb"
modal_bg = "#24273a"
modal_border_active = "#939ab7"
modal_cancel_fg = "#363a4f"
modal_cancel_bg = "#ee99a0"
modal_confirm_fg = "#363a4f"
modal_confirm_bg = "#91d7e3"

#-- Help Menu
help_menu_hotkey = "#91d7e3"
help_menu_title = "#ee99a0"

#-- Special
cursor = "#f4dbd6"
correct = "#a6da95"
error = "#ed8796"
hint = "#7dc4e4"
cancel = "#ee99a0"
