##############################################
#                                            #
#           Catppuccin Latte Theme           #
#                                            #
##############################################

# This theme was created by: https://github.com/GV14982 ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-latte"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#4c4f69"
full_screen_bg = "#eff1f5"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#1e66f5", "#ca9ee6"]

#-- File Panel
file_panel_fg = "#4c4f69"
file_panel_bg = "#eff1f5"
file_panel_border = "#9ca0b0"
file_panel_border_active = "#7287fd"
file_panel_top_directory_icon = "#40a02b"
file_panel_top_path = "#89b5fa"
file_panel_item_selected_fg = "#04a5e5"
file_panel_item_selected_bg = "#eff1f5"

#-- Footer
footer_fg = "#4c4f69"
footer_bg = "#eff1f5"
footer_border = "#9ca0b0"
footer_border_active = "#40a02b"

#-- Sidebar
sidebar_fg = "#4c4f69"
sidebar_bg = "#eff1f5"
sidebar_title = "#209fb5"
sidebar_border = "#eff1f5"
sidebar_border_active = "#40a02b"
sidebar_item_selected_fg = "#04a5e5"
sidebar_item_selected_bg = "#eff1f5"
sidebar_divider = "#7c7f93"

#-- Modals
modal_fg = "#4c4f69"
modal_bg = "#eff1f5"
modal_border_active = "#7c7f93"
modal_cancel_fg = "#eff1f5"
modal_cancel_bg = "#e64553"
modal_confirm_fg = "#eff1f5"
modal_confirm_bg = "#04a5e5"

#-- Help Menu
help_menu_hotkey = "#04a5e5"
help_menu_title = "#fe640b"

#-- Special
cursor = "#dc8a78"
correct = "#40a02b"
error = "#d20f39"
hint = "#209fb5"
cancel = "#e64553"
