##############################################
#                                            #
#           Catppuccin Frappe Theme          #
#                                            #
##############################################

# This theme was created by: https://github.com/GV14982 ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-frappe"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#a5adce"
full_screen_bg = "#303446"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#8caaee", "#ca9ee6"]

#-- File Panel
file_panel_fg = "#a5adce"
file_panel_bg = "#303446"
file_panel_border = "#737994"
file_panel_border_active = "#babbf1"
file_panel_top_directory_icon = "#a6d189"
file_panel_top_path = "#89b5fa"
file_panel_item_selected_fg = "#99d1db"
file_panel_item_selected_bg = "#303446"

#-- Footer
footer_fg = "#a5adce"
footer_bg = "#303446"
footer_border = "#737994"
footer_border_active = "#a6d189"

#-- Sidebar
sidebar_fg = "#a5adce"
sidebar_bg = "#303446"
sidebar_title = "#85c1dc"
sidebar_border = "#303446"
sidebar_border_active = "#e78284"
sidebar_item_selected_fg = "#99d1db"
sidebar_item_selected_bg = "#303446"
sidebar_divider = "#949cbb"

#-- Modals
modal_fg = "#a5adce"
modal_bg = "#303446"
modal_border_active = "#949cbb"
modal_cancel_fg = "#414559"
modal_cancel_bg = "#ea999c"
modal_confirm_fg = "#414559"
modal_confirm_bg = "#99d1db"

#-- Help Menu
help_menu_hotkey = "#99d1db"
help_menu_title = "#ea999c"

#-- Special
cursor = "#f2d5cf"
correct = "#a6d189"
error = "#e78284"
hint = "#85c1dc"
cancel = "#ea999c"
