##############################################
#                                            #
#           Catppuccin Mocha Theme           #
#                                            #
##############################################

# This theme was created by: https://github.com/AnshumanNeon ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-mocha"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#a6adc8"
full_screen_bg = "#1e1e2e"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#89b4fa", "#cba6f7"]

#-- File Panel
file_panel_fg = "#a6adc8"
file_panel_bg = "#1e1e2e"
file_panel_border = "#6c7086"
file_panel_border_active = "#b4befe"
file_panel_top_directory_icon = "#a6e3a1"
file_panel_top_path = "#89b5fa"
file_panel_item_selected_fg = "#98D0FD"
file_panel_item_selected_bg = "#1e1e2e"

#-- Footer
footer_fg = "#a6adc8"
footer_bg = "#1e1e2e"
footer_border = "#6c7086"
footer_border_active = "#a6e3a1"

#-- Sidebar
sidebar_fg = "#a6adc8"
sidebar_bg = "#1e1e2e"
sidebar_title = "#74c7ec"
sidebar_border = "#1e1e2e"
sidebar_border_active = "#f38ba8"
sidebar_item_selected_fg = "#A6DBF7"
sidebar_item_selected_bg = "#1e1e2e"
sidebar_divider = "#868686"

#-- Modals
modal_fg = "#a6adc8"
modal_bg = "#1e1e2e"
modal_border_active = "#868686"
modal_cancel_fg = "#383838"
modal_cancel_bg = "#eba0ac"
modal_confirm_fg = "#383838"
modal_confirm_bg = "#89dceb"

#-- Help Menu
help_menu_hotkey = "#89dceb"
help_menu_title = "#eba0ac"

#-- Special
cursor = "#f5e0dc"
correct = "#a6e3a1"
error = "#f38ba8"
hint = "#73c7ec"
cancel = "#eba0ac"
