##############################################
#                                            #
#           Gruvbox Dark Hard Theme          #
#                                            #
##############################################

# This theme was created by: https://github.com/frost-phoenix ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "gruvbox"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#fbf1c7"
full_screen_bg = "#1d2021"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#fb4934", "#b8bb26"]

#-- File Panel
file_panel_fg = "#fbf1c7"
file_panel_bg = "#1d2021"
file_panel_border = "#fbf1c7"
file_panel_border_active = "#98971a"
file_panel_top_directory_icon = "#689d6a"
file_panel_top_path = "#458588"
file_panel_item_selected_fg = "#d65d0e"
file_panel_item_selected_bg = ""

#-- Footer
footer_fg = "#fbf1c7"
footer_bg = "#1d2021"
footer_border = "#928374"
footer_border_active = "#d79921"

#-- Sidebar
sidebar_fg = "#fbf1c7"
sidebar_bg = "#1d2021"
sidebar_title = "#b16286"
sidebar_border = "#928374"
sidebar_border_active = "#b16286"
sidebar_item_selected_fg = "#d65d0e"
sidebar_item_selected_bg = ""
sidebar_divider = "#928374"

#-- Modals
modal_fg = "#fbf1c7"
modal_bg = "#1d2021"
modal_border_active = "#689d6a"
modal_cancel_fg = "#fb4934"
modal_cancel_bg = ""
modal_confirm_fg = "#b8bb26"
modal_confirm_bg = ""

#-- Help Menu
help_menu_hotkey = "#689d6a"
help_menu_title = "#b16286"

#-- Special
cursor = "#689d6a"
correct = "#98971a"
error = "#ff6969"
hint = "#468588"
cancel = "#838383"
