##############################################
#                                            #
#                Gruvbox Theme               #
#                                            #
##############################################

# This theme was created by: https://github.com/yorukot ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "gruvbox"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#ebdbb2"
full_screen_bg = "#282828"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#689d6a", "#fb4934"]

#-- File Panel
file_panel_fg = "#ebdbb2"
file_panel_bg = "#282828"
file_panel_border = "#868686"
file_panel_border_active = "#fff1c5"
file_panel_top_directory_icon = "#8ec07c"
file_panel_top_path = "#458588"
file_panel_item_selected_fg = "#d3869b"
file_panel_item_selected_bg = "#282828"

#-- Footer
footer_fg = "#ebdbb2"
footer_bg = "#282828"
footer_border = "#868686"
footer_border_active = "#d79921"

#-- Sidebar
sidebar_fg = "#ebdbb2"
sidebar_bg = "#282828"
sidebar_title = "#cc241d"
sidebar_border = "#282828"
sidebar_border_active = "#d79921"
sidebar_item_selected_fg = "#e8751a"
sidebar_item_selected_bg = "#282828"
sidebar_divider = "#868686"

#-- Modals
modal_fg = "#ebdbb2"
modal_bg = "#282828"
modal_border_active = "#868686"
modal_cancel_fg = "#ebdbb2"
modal_cancel_bg = "#6d6d6d"
modal_confirm_fg = "#ebdbb2"
modal_confirm_bg = "#ff4d00"

#-- Help Menu
help_menu_hotkey = "#8ec07c"
help_menu_title = "#ff4d00"

#-- Special
cursor = "#8ec07c"
correct = "#8ec07c"
error = "#ff6969"
hint = "#458588"
cancel = "#838383"
