##############################################
#                                            #
#                Monokai Theme               #
#                                            #
##############################################

# This theme was created by: https://github.com/CommandJoo ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "monokai"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#f8f8f2"
full_screen_bg = "#272822"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#66d9ef", "#ae81ff"]

#-- File Panel
file_panel_fg = "#f8f8f2"
file_panel_bg = "#272822"
file_panel_border = "#75715e"
file_panel_border_active = "#66d9ef"
file_panel_top_directory_icon = "#e6db74"
file_panel_top_path = "#e6db74"
file_panel_item_selected_fg = "#66d9ef"
file_panel_item_selected_bg = "#2e2e2e"

#-- Footer
footer_fg = "#f8f8f2"
footer_bg = "#272822"
footer_border = "#75715e"
footer_border_active = "#a9dc76"

#-- Sidebar
sidebar_fg = "#f8f8f2"
sidebar_bg = "#272822"
sidebar_title = "#66d9ef"
sidebar_border = "#75715e"
sidebar_border_active = "#f92672"
sidebar_item_selected_fg = "#66d9ef"
sidebar_item_selected_bg = "#272822"
sidebar_divider = "#75715e"

#-- Modals
modal_fg = "#f8f8f2"
modal_bg = "#272822"
modal_border_active = "#66d9ef"
modal_cancel_fg = "#75715e"
modal_cancel_bg = "#f92672"
modal_confirm_fg = "#75715e"
modal_confirm_bg = "#66d9ef"

#-- Help Menu
help_menu_hotkey = "#66d9ef"
help_menu_title = "#ae81ff"

#-- Special
cursor = "#66d9ef"
correct = "#a6e22e"
error = "#f92672"
hint = "#66d9ef"
cancel = "#e6db74"
