##############################################
#                                            #
#                 Nord Theme                 #
#                                            #
##############################################

# This theme was created by: https://github.com/rames-eltany ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "nord"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#e5e9f0"
full_screen_bg = "#2e3440"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#81a1c1", "#bf616a"]

#-- File Panel
file_panel_fg = "#e5e9f0"
file_panel_bg = "#2e3440"
file_panel_border = "#4c566a"
file_panel_border_active = "#d8dee9"
file_panel_top_directory_icon = "#88c0d0"
file_panel_top_path = "#88c0d0"
file_panel_item_selected_fg = "#bf616a"
file_panel_item_selected_bg = "#2e3440"

#-- Footer
footer_fg = "#e5e9f0"
footer_bg = "#2e3440"
footer_border = "#4c566a"
footer_border_active = "#b48ead"

#-- Sidebar
sidebar_fg = "#e5e9f0"
sidebar_bg = "#2e3440"
sidebar_title = "#81a1c1"
sidebar_border = "#2e3440"
sidebar_border_active = "#b48ead"
sidebar_item_selected_fg = "#88c0d0"
sidebar_item_selected_bg = "#2e3440"
sidebar_divider = "#868686"

#-- Modals
modal_fg = "#e5e9f0"
modal_bg = "#2e3440"
modal_border_active = "#868686"
modal_cancel_fg = "#e5e9f0"
modal_cancel_bg = "#4c566a"
modal_confirm_fg = "#e5e9f0"
modal_confirm_bg = "#bf616a"

#-- Help Menu
help_menu_hotkey = "#8fbcbb"
help_menu_title = "#81a1c1"

#-- Special
cursor = "#88c0d0"
correct = "#88c0d0"
error = "#bf616a"
hint = "#8fbcbb"
cancel = "#d8dee9"
