##############################################
#                                            #
#                OneDark Theme               #
#                                            #
##############################################

# This theme was created by: https://github.com/CommandJoo ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "onedark"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#a7aab0"
full_screen_bg = "#2c2d31"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#68aee8", "#bb70d2"]

#-- File Panel
file_panel_fg = "#a7aab0"
file_panel_bg = "#232326"
file_panel_border = "#737994"
file_panel_border_active = "#57a5e5"
file_panel_top_directory_icon = "#dbb671"
file_panel_top_path = "#dbb671"
file_panel_item_selected_fg = "#51a8b3"
file_panel_item_selected_bg = "#2c2d31"

#-- Footer
footer_fg = "#a7aab0"
footer_bg = "#232326"
footer_border = "#737994"
footer_border_active = "#8fb573"

#-- Sidebar
sidebar_fg = "#a7aab0"
sidebar_bg = "#232326"
sidebar_title = "#57a5e5"
sidebar_border = "#737994"
sidebar_border_active = "#de5d68"
sidebar_item_selected_fg = "#51a8b3"
sidebar_item_selected_bg = "#2c2d31"
sidebar_divider = "#818387"

#-- Modals
modal_fg = "#a7aab0"
modal_bg = "#35363b"
modal_border_active = "#51a8b3"
modal_cancel_fg = "#414559"
modal_cancel_bg = "#de5d68"
modal_confirm_fg = "#414559"
modal_confirm_bg = "#51a8b3"

#-- Help Menu
help_menu_hotkey = "#51a8b3"
help_menu_title = "#bb70d2"

#-- Special
cursor = "#68aee8"
correct = "#a6d189"
error = "#de5d68"
hint = "#68aee8"
cancel = "#c49060"
