##############################################
#                                            #
#               Rose Pine Theme              #
#                                            #
##############################################

# This theme was created by: https://github.com/pearcidar ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "rose-pine"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#e0def4"
full_screen_bg = "#191724"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#31784f", "#eb6f92"]

#-- File Panel
file_panel_fg = "#e0def4"
file_panel_bg = "#191724"
file_panel_border = "#403d52"
file_panel_border_active = "#6e6e86"
file_panel_top_directory_icon = "#9ccfd8"
file_panel_top_path = "#ebbcba"
file_panel_item_selected_fg = "#c4a7e7"
file_panel_item_selected_bg = "#191724"

#-- Footer
footer_fg = "#e0def4"
footer_bg = "#191724"
footer_border = "#403d52"
footer_border_active = "#f6c177"

#-- Sidebar
sidebar_fg = "#e0def4"
sidebar_bg = "#191724"
sidebar_title = "#6e6e86"
sidebar_border = "#191724"
sidebar_border_active = "#c4a7e7"
sidebar_item_selected_fg = "#f6c177"
sidebar_item_selected_bg = "#191724"
sidebar_divider = "#868686"

#-- Modals
modal_fg = "#e0def4"
modal_bg = "#191724"
modal_border_active = "#868686"
modal_cancel_fg = "#e0def4"
modal_cancel_bg = "#524f67"
modal_confirm_fg = "#e0def4"
modal_confirm_bg = "#eb6f92"

#-- Help Menu
help_menu_hotkey = "#f6c177"
help_menu_title = "#9ccfd8"

#-- Special
cursor = "#9ccfd8"
correct = "#8ec07c"
error = "#ff6969"
hint = "#31784f"
cancel = "#838383"
