##############################################
#                                            #
#               Sugarplum Theme              #
#                                            #
##############################################

# This theme was created by: https://github.com/lemonlime0x3C33 ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-macchiato"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#db7ddd"
full_screen_bg = "#111147"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#249a84", "#5ca8dc"]

#-- File Panel
file_panel_fg = "#db7ddd"
file_panel_bg = "#111147"
file_panel_border = "#a175d4"
file_panel_border_active = "#53aaa1"
file_panel_top_directory_icon = "#249a84"
file_panel_top_path = "#249a84"
file_panel_item_selected_fg = "#53b397"
file_panel_item_selected_bg = "#53b397"

#-- Footer
footer_fg = "#5ca8dc"
footer_bg = "#111147"
footer_border = "#a175d4"
footer_border_active = "#53aaa1"

#-- Sidebar
sidebar_fg = "#d0beee"
sidebar_bg = "#111147"
sidebar_title = "#db7ddd"
sidebar_border = "#a175d4"
sidebar_border_active = "#53aaa1"
sidebar_item_selected_fg = "#249a84"
sidebar_item_selected_bg = "#111147"
sidebar_divider = "#565f89"

#-- Modals
modal_fg = "#98c7a3"
modal_bg = "#111147"
modal_border_active = "#53aaa1"
modal_cancel_fg = "#7c4094"
modal_cancel_bg = "#7c4094"
modal_confirm_fg = "#7c4094"
modal_confirm_bg = "#7c4094"

#-- Help Menu
help_menu_hotkey = "#7dcfff"
help_menu_title = "#73daca"

#-- Special
cursor = "#53b397"
correct = "#524094"
error = "#2082a6"
hint = "#91d4c2"
cancel = "#b53dff"
