##############################################
#                                            #
#              Tokyo Night Theme             #
#                                            #
##############################################

# This theme was created by: https://github.com/pearcidar ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-macchiato"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#a9b1d6"
full_screen_bg = "#1a1b26"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#7aa2f7", "#bb9af7"]

#-- File Panel
file_panel_fg = "#a9b1d6"
file_panel_bg = "#1a1b26"
file_panel_border = "#414868"
file_panel_border_active = "#b4befe"
file_panel_top_directory_icon = "#73daca"
file_panel_top_path = "#7aa2f7"
file_panel_item_selected_fg = "#2ac3de"
file_panel_item_selected_bg = "#1a1b26"

#-- Footer
footer_fg = "#a9b1d6"
footer_bg = "#1a1b26"
footer_border = "#414868"
footer_border_active = "#73daca"

#-- Sidebar
sidebar_fg = "#a9b1d6"
sidebar_bg = "#1a1b26"
sidebar_title = "#73daca"
sidebar_border = "#24283b"
sidebar_border_active = "#f7768e"
sidebar_item_selected_fg = "#7dcfff"
sidebar_item_selected_bg = "#1a1b26"
sidebar_divider = "#565f89"

#-- Modals
modal_fg = "#a9b1d6"
modal_bg = "#1a1b26"
modal_border_active = "#73daca"
modal_cancel_fg = "#24383b"
modal_cancel_bg = "#e0af68"
modal_confirm_fg = "#24283b"
modal_confirm_bg = "#9ece6a"

#-- Help Menu
help_menu_hotkey = "#7dcfff"
help_menu_title = "#73daca"

#-- Special
cursor = "#ff9e64"
correct = "#9ece6a"
error = "#f7768e"
hint = "#7dcfff"
cancel = "#ff9e64"
