# =================================================================================================
# Here is global, all global key cant conflicts with other hotkeys
confirm = ['enter', 'l']
quit = ['q', 'esc'] # (q)uit
# movement
list_up = ['up', 'k'] # most user use
list_down = ['down', 'j'] # most user use
# file panel controll
close_file_panel = ['w', '']
create_new_file_panel = ['n', ''] # (n)ew file panel
next_file_panel = ['tab', 'L']
previous_file_panel = ['shift+left', 'H']
# change focus
focus_on_process_bar = ['p', ''] # (p)rocessbar
focus_on_sidebar = ['s', ''] # (s)idebar
focus_on_metadata = ['m', ''] # (m)etadata
# create file/directory and rename 
file_panel_item_create = ['ctrl+n', ''] # (n)ew file or folder
file_panel_item_rename = ['ctrl+r', ''] # (r)name
# file operate
copy_items = ['ctrl+c', '']  # Most systems are for (c)opy
paste_items = ['ctrl+v', ''] # Most systems are for pasting
cut_items = ['ctrl+x', ''] # Most systems are for cut
delete_items = ['ctrl+d', 'delete'] #(d)elete
# compress and extract
extract_file = ['ctrl+e', ''] # (e)xtract
compress_file = ['ctrl+a', ''] # (a)rchive file
# editor
oepn_file_with_editor = ['e', ''] # (e)ditor
open_current_directory_with_editor = ['E', ''] # (E)ditor
# else
pinned_directory = ['P', ''] # (P)inned
toggle_dot_file = ['.', ''] # (.)dot
change_panel_mode = ['v', ''] # (v)isual
open_help_menu = ['?', '']
# =================================================================================================
# Here is typing hotkey can conflict with all hotkeys
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+c', 'esc']
# =================================================================================================
# Here is normal mode hotkey you can conflicts with other mode (cant conflicts with global hotkey)
parent_directory = ['h', 'backspace'] 
search_bar = ['/', '']
# =================================================================================================
# Here is select mode hotkey you can conflicts with other mode (cant conflicts with global hotkey)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['A', '']
