name: "Welcome First-Time Contributor"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ðŸ‘‹ Hi there, and welcome to **superfile**!

            Thanks for opening your first issue. We really appreciate your interest and involvement.

            A maintainer might ask you for more details or clarification to better understand the issue.  
            Thatâ€™s totally normal and helps us solve the problem more effectively.

            If you plan to submit a PR, make sure to check our [Contribution Guide](https://github.com/yorukot/superfile/blob/main/CONTRIBUTING.md)

          pr-message: |
            ðŸŽ‰ Thank you for your first contribution to **superfile**!

            Weâ€™re really excited to have you here ðŸ™Œ

            A maintainer might ask you to make a few changes before we can merge this PR.  
            Thatâ€™s totally normal and part of the process. Donâ€™t worry, weâ€™ll help guide you through it.

            ðŸ‘‰ Please also take a moment to review our [Contribution Guide](https://github.com/yorukot/superfile/blob/main/CONTRIBUTING.md)

            If you have any questions, feel free to open a [Discussion](https://github.com/yorukot/superfile/discussions) or just ask in the comments!
